In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('../../datasets/Used Car Dataset.csv')

In [17]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [18]:
s1 = df['transmission'].apply(lambda x:x in ['Manual','Automatic'])

In [19]:
df.shape

(1553, 15)

In [20]:
sum(s1)

1503

In [21]:
df[s1]

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,1547,2022 Maruti Ertiga VXI CNG,May-22,Third Party insurance,CNG,7,26500,First Owner,Manual,2022,26.11,1462.0,1462.0,8663.0,11.50
1548,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.00,11345.0,11345.0,250.0,17.41
1550,1550,2017 Honda WR-V i-VTEC S,Jun-17,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.50,1199.0,1199.0,887.0,5.85
1551,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.78,999.0,999.0,75.0,4.75
1552,1552,2018 Maruti Swift Dzire VXI,May-18,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.85,1197.0,1197.0,8314.0,6.10

In [22]:
df = df[df['transmission'].isin(['Manual', 'Automatic'])]
df

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,1547,2022 Maruti Ertiga VXI CNG,May-22,Third Party insurance,CNG,7,26500,First Owner,Manual,2022,26.11,1462.0,1462.0,8663.0,11.50
1548,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.00,11345.0,11345.0,250.0,17.41
1550,1550,2017 Honda WR-V i-VTEC S,Jun-17,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.50,1199.0,1199.0,887.0,5.85
1551,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.78,999.0,999.0,75.0,4.75
1552,1552,2018 Maruti Swift Dzire VXI,May-18,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.85,1197.0,1197.0,8314.0,6.10

In [25]:
df['registration_year'].apply(lambda x:int(x.split('-')[-1][-2:]))
list(df['registration_year'].value_counts().index)

['Jul-18',
 'Jul-17',
 'Aug-18',
 'May-17',
 'Oct-18',
 'Nov-18',
 'Nov-17',
 'Nov-19',
 'Nov-15',
 'Oct-17',
 'Mar-19',
 'Jul-16',
 'Nov-20',
 'Jun-18',
 'Jul-19',
 'Nov-21',
 'Dec-18',
 '2012',
 'Aug-17',
 'Sep-18',
 'Mar-20',
 'Apr-19',
 'Oct-20',
 'May-19',
 'Jun-19',
 'Oct-19',
 'Jun-17',
 'Apr-18',
 'Sep-19',
 'May-15',
 'Sep-15',
 'Feb-19',
 'Aug-19',
 'Apr-16',
 'Oct-15',
 'Nov-14',
 'Feb-18',
 'Dec-22',
 'Aug-20',
 'Aug-22',
 'Jan-16',
 'May-18',
 'Oct-14',
 '2017',
 'Dec-21',
 'Aug-16',
 'Mar-21',
 'Jan-20',
 'Mar-18',
 '2018',
 'Dec-20',
 'Feb-22',
 'Jan-22',
 '2014',
 'Jul-21',
 'Dec-15',
 'Sep-16',
 'Jul-14',
 'Aug-21',
 'Jun-14',
 'Dec-17',
 'Nov-22',
 'Mar-16',
 'Jan-14',
 'Jan-21',
 'Oct-16',
 'Jun-15',
 'Jul-20',
 'Aug-15',
 'Feb-20',
 'Sep-17',
 'May-22',
 'May-16',
 'May-14',
 'Mar-17',
 'Dec-16',
 'Jul-22',
 'Jun-21',
 'Jun-20',
 'Dec-19',
 'Feb-15',
 'Jan-19',
 'Jan-17',
 'Nov-13',
 '2016',
 'Nov-16',
 '2015',
 'Jun-16',
 'Oct-22',
 'Jul-15',
 'Sep-21',
 'Apr-15',
 'Jul-12',
 'Nov-12',
 'Sep-20',
 'Apr-21',
 'May-11',
 'Aug-14',
 'Sep-23',
 'Oct-13',
 'Mar-14',
 'Apr-17',
 '2013',
 'Feb-16',
 'Nov-23',
 'Apr-23',
 'Oct-21',
 'Mar-13',
 'Mar-15',
 'Aug-11',
 'Jul-13',
 'Feb-12',
 'Dec-14',
 'Feb-23',
 'Jan-23',
 'Jun-22',
 '2009',
 'May-13',
 'Jun-11',
 '2023',
 'Aug-23',
 'Sep-22',
 'Feb-21',
 '2020',
 'Feb-17',
 'Jul-23',
 'Sep-13',
 'May-23',
 'Oct-10',
 'Apr-20',
 'Mar-23',
 'Jan-18',
 'Sep-14',
 'Mar-22',
 'Dec-13',
 'Jun-12',
 'Apr-22',
 '2021',
 'Dec-12',
 'Jun-10',
 '2019',
 'May-10',
 'Mar-11',
 'May-21',
 'Aug-13',
 '2022',
 'Jan-10',
 'Apr-11',
 'Oct-12',
 'Jan-12',
 'Dec-11',
 'Jan-15',
 'Mar-12',
 'Jan-09',
 'Mar-09',
 'Apr-12',
 '2010',
 'Jun-13',
 'Nov-10',
 'Jun-23',
 'Jan-11',
 '2011',
 'Jul-11',
 'May-12',
 'Feb-13',
 'Apr-13',
 'Nov-09',
 'Jul-10',
 'Nov-11',
 'May-09',
 'Aug-10',
 'Apr-14',
 '2007',
 'Sep-12',
 'Sep-11',
 'Dec-09',
 'Mar-10']